app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// redirect to types.index
Route::get('/', function()
    {
        return redirect()->route('types.index');
    }
);

/*           TYPES                          */

Route::resource('types', 'TypeController',      ['only' => ['index', 'store', 'edit', 'destroy']]);


/*           FIELDS                         */

Route::resource('fields', 'FieldController',    ['only' => ['store', 'destroy']]);


/*           BLOCKS                         */

Route::resource('blocks', 'BlockController',    ['only' => ['index', 'store', 'edit', 'update', 'destroy']]);

app/Block.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Block extends Model
{
    public $timestamps = false;

    public function type()
    {
        return $this->belongsTo('App\Type');
    }

    public function fields()
    {
        return $this->belongsToMany('App\Field')->withPivot('value');
    }

    // cascade delete
    protected static function boot() {
        parent::boot();

        static::deleting(function($block) {
            //$block->type()->fields();
        });
    }


}

app/Field.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Field extends Model
{
    public $timestamps = false;

    public function type()
    {
        return $this->belongsTo('App\Type');
    }

    public function blocks()
    {
        return $this->belongsToMany('App\Block')->withPivot('value');
    }
    
    
}

app/Type.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Type extends Model
{
    public $timestamps = false;

    public function blocks()
    {
        return $this->hasMany('App\Block');
    }

    public function fields()
    {
        return $this->hasMany('App\Field');
    }

    // cascade delete
    protected static function boot() {
        parent::boot();

        static::deleting(function($type) {
            // delete record in pivot table
            foreach ($type->fields()->get() as $field)
                $field->blocks()->detach();
            // delete fields
            $type->fields()->delete();
        });
    }
}

app/Http/Controllers/BlockController.php
<?php

namespace App\Http\Controllers;

use App\Block;
use App\Field;
use App\Type;
use Illuminate\Http\Request;

use App\Http\Requests;

class BlockController extends Controller
{
    public function index()
    {
        // all blocks
        $blocks = Block::all();
        // all types for select options
        $types = Type::all();
        return view('app.blocks',['blocks' => $blocks, 'types' => $types]);
    }
    
    
    public function store(Request $request)
    {
        // validate
        $this->validate($request,
            [
                'name'	=> 'required',
                'type'  => 'required|integer'
            ]
        );

        // create new block
        $block = new Block();
        $block->name = $request['name'];
        $block->type_id = $request['type'];
        $block->save();

        // fields for current type
        $fieldsType = Type::find($request['type'])->fields()->get();

        // for fields set empty values in pivot table
        foreach($fieldsType as $k => $v){
            $block->fields()->attach($v->id, ['value' => '']);
        }

        // type name of new block
        $type_name = Type::where('id', $request['type'])->first()->name;

        // for AJAX response (update html)
        $response = [
            'id' => $block->id,
            'name' => $block->name,
            'type' => $type_name
        ];
        return $response;
    }

    public function edit($id)
    {
        // current block
        $block = Block::find($id);

        // get fields
        $fields = $block->fields()->get();

        return view('app.blocksEdit',['block' => $block, 'fields' => $fields]);
    }

    
    public function update($id, Request $request)
    {
        // validate
        $this->validate($request,
            [
                'name'	=> 'required|string',
            ]
        );
        // current block
        $block = Block::find($id);
        // update block
        $block->name = $request['name'];
        $block->save();

        // update fields for current block
        if(count($request['dynamic']) > 0){
            foreach($request['dynamic'] as $k => $v) {
                $field = Field::find($k)->blocks()->find($id);
                $field->pivot->value = $v;
                $field->pivot->save();
            }
        }
        return $field;
    }


    public function destroy($id)
    {
        // current block
        $block = Block::find($id);

        // current type block
        $id_type = $block->type_id;

        // delete pivot values
        if(Type::where('id',$id_type)->count()){
            $fieldsType = Type::find($id_type)->fields()->get();
            foreach($fieldsType as $k => $v){
                $block->fields()->detach($v->id);
            }
        }

        // delete block
        $block->delete();
    }
    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FieldController.php
<?php

namespace App\Http\Controllers;

use App\Field;
use App\Type;
use Illuminate\Http\Request;

use App\Http\Requests;

class FieldController extends Controller
{
    
    public function store(Request $request)
    {
        // validation
        $this->validate($request,
            [
                'name'	=> 'required',
                'type'  => 'required|integer'
            ]
        );
        
        // new field
        $field = new Field();
        $field->name = $request['name'];
        $field->type_id = $request['type'];
        $field->save();

        // for field set empty values in pivot table
        $blocksType = Type::find($request['type'])->blocks()->get();
        foreach($blocksType as $k => $v){
            $field->blocks()->attach($v->id, ['value' => '']);
        }
        
        // for AJAX
        $response = [
            'id' => $field->id,
            'name' => $field->name
        ];
        return $response;
    }


    public function destroy($id)
    {
        // delete field
        $field = Field::where('id', $id)->first();
        $field->delete();
    }
    
}

app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use App\Type;
use Illuminate\Http\Request;

use App\Http\Requests;

class TypeController extends Controller
{
    public function index()
    {
        // all fields
        $types = Type::all();
        
        return view('app.types',['types' => $types]);
    }

    
    public function store(Request $request)
    {
        // validation
        $this->validate($request,
            [
                'name'	=> 'required'
            ]
        );
        
        // create new type
        $type = new Type();
        $type->name = $request['name'];
        $type->save();
        
        // for AJAX
        $response = [
            'id' => $type->id,
            'name' => $type->name
        ];
        return $response;
    }
    

    public function edit($id)
    {
        // type for edit
        $type = Type::where('id', $id)->first();
        
        return view('app.typesEdit',['type' => $type]);
    }

    
    public function destroy($id)
    {
        // delete type
        $type = Type::where('id', $id)->first();
        $type->delete();
    }
    
}

resources/views/app/blocks.blade.php
@extends('layouts.master')

@section('caption')
    Blocks
@stop

@section('content')
    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Type</th>
                <th>Actions</th>
            </tr>
            @foreach($blocks as $block)
                <tr class="item">
                    <td>{{$block->id}}</td>
                    <td>{{$block->name}}</td>
                    <td>{{$block->type['name']}}</td>
                    <td>
                        <a class="btn btn-primary" href="{{route('blocks.edit', $block->id)}}">Edit</a>
                        <a class="btn btn-danger itemDestroy" href="{{route('blocks.destroy', $block->id)}}">Delete</a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <form action="{{route('blocks.store')}}" method="post" class="form-inline itemStore">
        <div class="form-group">
            <input class="form-control" name="name" placeholder="name">
        </div>

        <div class="form-group">
            <select class="form-control" name="type">
                @foreach($types as $type)
                    <option value="{{$type->id}}">{{$type->name}}</option>
                @endforeach
            </select>
        </div>
        {{csrf_field()}}
        <input class="btn btn-success" type="submit" value="Add">
    </form>
@stop


@section('script')
    <script>
        $(function () {
            // ajax delete item
            deleteEntityTable();

            // ajax add item
            $('form.itemStore').on('submit', function (e) {
                e.preventDefault();
                var table = $('table.table');
                var form = $(this);
                $.ajax({
                    type: "POST",
                    url: form.attr('action'),
                    data: form.serialize(),
                    success: function(response){
                        var itemTable = '<tr class="item">' +
                                '<td>' + response.id +'</td>' +
                                '<td>'+ response.name +'</td>' +
                                '<td>'+ response.type +'</td>' +
                                '<td>' +
                                '<a class="btn btn-primary" href="/blocks/'+ response.id +'/edit">Edit</a>' +
                                '<a style="margin-left: 4px" class="btn btn-danger itemDestroy" href="/blocks/'+ response.id +'">Delete</a>' +
                                '</td>' +
                                '</tr>';
                        table.append(itemTable);
                        form.find('input[name="name"]').val('');
                    }
                });
            });
        });
    </script>
@stop

resources/views/app/blocksEdit.blade.php
@extends('layouts.master')

@section('caption')
    Edit block
@stop

@section('content')
    <form action="{{route('blocks.update', $block->id)}}" method="post" class="blocksUpdate">
        <div class="form-group">
            <label for="name">Name</label>
            <input id="name" class="form-control" name="name" value="{{$block->name}}"><br>
        </div>

        <hr>
        @foreach($fields as $field)
            <div class="form-group">
                <label for="{{$field->id}}">{{$field->name}}</label>
                <input class="form-control" id="{{$field->id}}" name="dynamic[{{$field->id}}]" value="{{$field->pivot->value}}"><br>
            </div>
        @endforeach
        <br>
        {{csrf_field()}}
        <input type="hidden" name="block_id" value="{{$block->id}}">
        <input type="hidden" name="_method" value="PUT">
        <input class="btn btn-primary" type="submit" value="Save">
    </form>
@stop


@section('script')
    <script>
        $(function () {
            // ajax update fields
            $('form.blocksUpdate').on('submit', function (e) {
                e.preventDefault();
                var form = $(this);
                $.ajax({
                    type: "POST",
                    url: '{{route('blocks.update', $block->id)}}',
                    data: form.serialize(),
                    success: function(response){
                        console.log(response);
                    }
                });
            });
        });
    </script>
@stop

resources/views/app/types.blade.php
@extends('layouts.master')

@section('caption')
    Types
@stop

@section('content')
    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Actions</th>
            </tr>
            @foreach($types as $type)
                <tr class="item">
                    <td>{{$type->id}}</td>
                    <td>{{$type->name}}</td>
                    <td>
                        <a class="btn btn-primary" href="{{route('types.edit', $type->id)}}">Fields</a>
                        <a class="btn btn-danger itemDestroy" href="{{route('types.destroy', $type->id)}}">Delete</a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <br>
    <form action="{{route('types.store')}}" method="post" class="form-inline itemStore">
        <div class="form-group">
            <input name="name" class="form-control" placeholder="Name">
        </div>
        <input type="submit" class="btn btn-success" value="Add">
        {{csrf_field()}}
    </form>
@stop

@section('script')
    <script>
        $(function () {
            // ajax delete item
            deleteEntityTable();

            // ajax add item
            $('form.itemStore').on('submit', function (e) {
                e.preventDefault();
                var table = $('table.table');
                var form = $(this);
                $.ajax({
                    type: "POST",
                    url: form.attr('action'),
                    data: form.serialize(),
                    success: function(response){
                        var itemTable = '<tr class="item">' +
                                        '<td>' + response.id +'</td>' +
                                        '<td>'+ response.name +'</td>' +
                                        '<td>' +
                                            '<a class="btn btn-primary" href="/types/'+ response.id +'/edit">Fields</a>' +
                                            '<a style="margin-left: 4px" class="btn btn-danger itemDestroy" href="/types/'+ response.id +'">Delete</a>' +
                                        '</td>' +
                                        '</tr>';
                        table.append(itemTable);
                        form.find('input[name="name"]').val('');
                    }
                });
            });
        });
    </script>
@stop

resources/views/app/typesEdit.blade.php
@extends('layouts.master')

@section('caption')
    Fields of type "{{$type->name}}"
@stop

@section('content')
    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Actions</th>
            </tr>
            @foreach($type->fields as $field)
                <tr class="item">
                    <td>{{$field->id}}</td>
                    <td>{{$field->name}}</td>
                    <td>
                        <a class="btn btn-danger itemDestroy" href="{{route('fields.destroy', $field->id)}}">Delete</a>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <br>
    <form action="{{route('fields.store')}}" method="post" class="form-inline itemStore">
        <div class="form-group">
            <input name="name" class="form-control" placeholder="Name">
        </div>
        <input type="submit" class="btn btn-success" value="Add">
        <input type="hidden" name="type" value="{{$type->id}}">
        {{csrf_field()}}
    </form>
@stop


@section('script')
    <script>
        $(function () {
            // ajax delete item
            deleteEntityTable();

            // ajax add item
            $('form.itemStore').on('submit', function (e) {
                e.preventDefault();
                var table = $('table.table');
                var form = $(this);
                $.ajax({
                    type: "POST",
                    url: form.attr('action'),
                    data: form.serialize(),
                    success: function(response){
                        var itemTable = '<tr class="item">' +
                                '<td>' + response.id +'</td>' +
                                '<td>'+ response.name +'</td>' +
                                '<td>' +
                                    '<a class="btn btn-danger itemDestroy" href="/fields/'+ response.id +'">Delete</a>' +
                                '</td>' +
                                '</tr>';
                        table.append(itemTable);
                        form.find('input[name="name"]').val('');
                    }
                });
            });
        });
    </script>
@stop

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Inlusion test</title>
    <link rel="shortcut icon" href="http://inlu.net/favicon.png">
    <link rel="apple-touch-icon" sizes="60x60" href="http://inlu.net/favicon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="http://inlu.net/favicon.png">
    <link rel="manifest" href="http://inlu.net/assets/images/favicons/manifest.json">
    <meta name="csrf-token" content="Iu2UVRnU5EEGVDDPUcUOVVCtqpHUh5zg2KR21byU">
    <meta name="msapplication-TileColor" content="#000000">
    <meta name="msapplication-TileImage" content="http://inlu.net/favicon.png">
    <meta name="theme-color" content="#000000">
    <!-- Bootstrap -->
    <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    @include('partials.header')
    <div class="container">
        <div class="row">
            <h1>@yield('caption')</h1>
            <br>
            @yield('content')
        </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
    <script>
        function deleteEntityTable() {
            $('table').on('click', '.itemDestroy', function (e) {
                e.preventDefault();
                var item = $(this).closest('.item');
                var link = $(this).attr('href');
                $.ajax({
                    type: "POST",
                    url: link,
                    data: '_method=DELETE&_token={{csrf_token()}}',
                    success: function(data){
                        item.remove();
                    }
                });
            });
        }
    </script>
    @yield('script')
</body>
</html>

resources/views/partials/header.blade.php
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Inlusion test</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="{{ Request::is('types') ? 'active' : '' }}"><a href="{{route('types.index')}}">Types</a></li>
                <li class="{{ Request::is('blocks') ? 'active' : '' }}"><a href="{{route('blocks.index')}}">Blocks</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>